sudo: true
language: elixir
elixir:
  - 1.9.4
otp_release:
  - 22.2
script:
  - mix analyze --non-interactive
after_success:
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - _build
    - deps
